service: cogeo-mosaic-naip

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'production'}
  region: 'us-west-2'

  deploymentBucket: ${opt:bucket}

  # Add Tags to resources
  stackTags:
    Project: cogeo

  apiGateway:
    binaryMediaTypes:
      - '*/*'
    minimumCompressionSize: 1

  # Add other buckets here if needed
  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "*"
     Resource:
       - "arn:aws:s3:::${opt:bucket}*"
  -  Effect: "Allow"
     Action:
       - "s3:GetObject"
       - "s3:HeadObject"
     Resource:
       - "arn:aws:s3:::*"

  # httpApi:
  #   timeout: 15 # Restrict endpoints to timeout in 15s
  #   cors: true

package:
  artifact: ../../package.zip

functions:
  app:
    handler: cogeo_mosaic_tiler.handlers.app.app
    memorySize: 2048
    timeout: 10
    layers:
      - arn:aws:lambda:${self:provider.region}:524387336408:layer:gdal30-py37-cogeo:8
    environment:
      AWS_REQUEST_PAYER: requester
      CPL_TMPDIR: /tmp
      GDAL_CACHEMAX: 25%
      GDAL_DATA: /opt/share/gdal
      GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
      GDAL_HTTP_MULTIPLEX: YES
      GDAL_HTTP_VERSION: 2
      MAX_THREADS: 10
      MOSAIC_DEF_BUCKET: ${opt:bucket}
      PROJ_LIB: /opt/share/proj
      PYTHONWARNINGS: ignore
      VSI_CACHE: TRUE
      VSI_CACHE_SIZE: 536870912
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
